### ISSUE TITLE
Thoughts on KCC?

### ISSUE THREAD

**Issue by axu2** [tsopeh/mapaki#1]
This is the OG Kindle Comic Converter

https://github.com/ciromattia/kcc

**Comment by tsopeh** [comment]
KCC is an awesome project, and I wouldn't even consider reading manga on Kindle if I haven't used it in the past. The one drawback it has it that it cannot produce a single file output larger than 400MB ([it's a _kindlegen_ limitation](https://github.com/ciromattia/kcc/issues/563)) without margins. Since then, I've found another project that have achieved that, but did some other stuff that I really didn't care about; that's when I've decided to create _mapaki_.

**Comment by axu2** [comment]
Cool, working around kindlegen limitations I see.

**Comment by Levuuuu** [comment]
> KCC is an awesome project, and I wouldn't even consider reading manga on Kindle if I haven't used it in the past. The one drawback it has it that it cannot produce a single file output larger than 400MB ([it's a _kindlegen_ limitation](https://github.com/ciromattia/kcc/issues/563)) without margins. Since then, I've found another project that have achieved that, but did some other stuff that I really didn't care about; that's when I've decided to create _mapaki_.

Hey I tried to use mapaki on windows but when i use the mapaki command in cmd it says that there is no mapaki command. And I don't know how to add it. Can you help me?
